# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestros', '0003_peq_mae_tipo_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atenciones',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, max_length=25, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_tipo_atencion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atenci\xf3n',
                'verbose_name_plural': 'Atenciones',
            },
        ),
    ]
