# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0002_atenciones_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atenciones',
            name='dni',
        ),
    ]
