# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_peq_mae_capacitaciones'),
        ('atenciones', '0003_remove_atenciones_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciones',
            name='capacitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_capacitaciones'),
        ),
    ]
