# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0004_atenciones_capacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atenciones',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
