# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0005_auto_20180518_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciones',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
