# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0006_atenciones_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciones',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
