# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('persona_contacto', models.CharField(max_length=255)),
                ('numero_celular', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
            },
        ),
        migrations.CreateModel(
            name='ContratistaPrincipal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('persona_contacto', models.CharField(max_length=255)),
                ('numero_celular', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contratista Principal',
                'verbose_name_plural': 'Contratistas Principales',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProyectoContratistas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contratista_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.ContratistaPrincipal')),
                ('contratistas', models.ManyToManyField(to='contratistas.Contratista')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto Contratistas',
                'verbose_name_plural': 'Proyecto Contratistas',
            },
        ),
        migrations.CreateModel(
            name='SubContratista',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('persona_contacto', models.CharField(max_length=255)),
                ('numero_celular', models.CharField(max_length=255)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.Contratista')),
            ],
            options={
                'verbose_name': 'SubContratista',
                'verbose_name_plural': 'SubContratistas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proyectocontratistas',
            unique_together=set([('proyecto', 'contratista_principal')]),
        ),
    ]
