# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maestros.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestros', '0001_initial'),
        ('contratistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('condiciones_adicionales', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.Contratista')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_lugares')),
                ('remuneracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_remuneracion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'permissions': (('autorizar_convocatoria', 'Puede autorizar convocatoria'),),
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaPuesto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_vacantes', models.PositiveIntegerField()),
                ('edad_minima', models.PositiveIntegerField()),
                ('edad_maxima', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.Convocatoria')),
                ('duracion_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_duracion_contrato')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia')),
                ('familia_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_puesto')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_rangos')),
                ('requisitos', models.ManyToManyField(to='maestros.PEQ_MAE_requisitos')),
                ('sub_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_sub_especialidad')),
            ],
            options={
                'verbose_name': 'Convocatorias Puesto',
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria_puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Persona')),
                ('tags', models.ManyToManyField(to='maestros.PEQ_MAE_tags')),
            ],
            options={
                'verbose_name': 'Convocatoria Tag',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPostulacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalle_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_detalle_documentacion')),
            ],
            options={
                'verbose_name': 'Documentos Postulacion',
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasesIngreso',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boleta_de_pago', models.FileField(blank=True, null=True, upload_to=maestros.helpers.get_file_path)),
                ('pdt', models.FileField(blank=True, null=True, upload_to=maestros.helpers.get_file_path)),
                ('registro_informacion_laboral', models.FileField(blank=True, null=True, upload_to=maestros.helpers.get_file_path)),
                ('carnet_extranjeria', models.FileField(blank=True, null=True, upload_to=maestros.helpers.get_file_path)),
                ('tramite_calidad_migratoria', models.FileField(blank=True, null=True, upload_to=maestros.helpers.get_file_path)),
                ('orden_servicio', models.FileField(blank=True, null=True, upload_to=maestros.helpers.get_file_path)),
                ('convocatoria_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('criterio_aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_criterios_aprobacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='PEQ_INT_convocatoria_academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indispensable', models.BooleanField(default=False)),
                ('porcentaje_cumplimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_registro', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'normal'), (1, 'criterio')], default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_carreras')),
                ('convocatoria_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('estado_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_estado_grado')),
                ('familia_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_carreras')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_grado')),
            ],
            options={
                'verbose_name': 'Convocatorias Acad\xe9mico',
            },
        ),
        migrations.CreateModel(
            name='PEQ_INT_convocatoria_cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('indispensable', models.BooleanField(default=False)),
                ('porcentaje_cumplimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_registro', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'normal'), (1, 'criterio')], default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_cursos')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_tipo_cursos')),
            ],
            options={
                'verbose_name': 'Convocatorias curso',
            },
        ),
        migrations.CreateModel(
            name='PEQ_INT_convocatoria_documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indispensable', models.BooleanField(default=False)),
                ('porcentaje_cumplimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_registro', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'normal'), (1, 'criterio')], default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('detalle_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_detalle_documentacion')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_documentacion')),
            ],
            options={
                'verbose_name': 'Convocatorias curso',
            },
        ),
        migrations.CreateModel(
            name='PEQ_INT_convocatoria_experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_cumplimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_registro', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'normal'), (1, 'criterio')], default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_tiempo_experiencia', verbose_name='Tiempo')),
                ('familia_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_puesto')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_rangos')),
                ('sub_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_sub_especialidad')),
            ],
            options={
                'verbose_name': 'Convocatorias Experiencia',
            },
        ),
        migrations.CreateModel(
            name='PEQ_INT_estado_convocatoria',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.Convocatoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_estados_convocatoria')),
            ],
            options={
                'verbose_name': 'Convocatorias Fecha',
            },
        ),
        migrations.CreateModel(
            name='PEQ_INT_estado_postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llamado', models.BooleanField(default=False)),
                ('quiero_participar', models.BooleanField(default=False)),
                ('entrevista', models.BooleanField(default=False)),
                ('apto', models.BooleanField(default=False)),
                ('visitado', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_estados_postulacion')),
                ('observaciones', models.ManyToManyField(blank=True, to='convocatorias.Observaciones')),
            ],
            options={
                'verbose_name': 'Estado Postulacion',
            },
        ),
        migrations.CreateModel(
            name='PlantillaCriteriosAvanzados',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('academico', models.ManyToManyField(blank=True, to='convocatorias.PEQ_INT_convocatoria_academico')),
                ('cursos', models.ManyToManyField(blank=True, to='convocatorias.PEQ_INT_convocatoria_cursos')),
                ('experiencia', models.ManyToManyField(blank=True, to='convocatorias.PEQ_INT_convocatoria_experiencia')),
            ],
            options={
                'verbose_name': 'Criterios Avanzados',
                'verbose_name_plural': 'Criterios Avanzados',
            },
        ),
        migrations.CreateModel(
            name='PostulacionConvocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_postulacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria_puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.ConvocatoriaPuesto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Persona')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_rango_seleccion')),
            ],
            options={
                'verbose_name': 'Convocatorias Postulante',
            },
        ),
        migrations.AddField(
            model_name='peq_int_estado_postulacion',
            name='postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.PostulacionConvocatoria'),
        ),
        migrations.AddField(
            model_name='documentopostulacion',
            name='estado_postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.PEQ_INT_estado_postulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacionconvocatoria',
            unique_together=set([('convocatoria_puesto', 'persona')]),
        ),
        migrations.AlterUniqueTogether(
            name='peq_int_estado_postulacion',
            unique_together=set([('postulacion', 'estado')]),
        ),
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_experiencia',
            unique_together=set([('convocatoria_puesto', 'especialidad', 'familia_puesto', 'rango', 'tipo_registro')]),
        ),
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_documentos',
            unique_together=set([('convocatoria_puesto', 'detalle_documento', 'tipo_registro')]),
        ),
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_cursos',
            unique_together=set([('convocatoria_puesto', 'tipo', 'tipo_registro')]),
        ),
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_academico',
            unique_together=set([('convocatoria_puesto', 'familia_carrera', 'carrera', 'grado', 'estado_grado', 'tipo_registro')]),
        ),
        migrations.AlterUniqueTogether(
            name='pasesingreso',
            unique_together=set([('persona', 'convocatoria_puesto')]),
        ),
        migrations.AlterUniqueTogether(
            name='documentopostulacion',
            unique_together=set([('detalle_documento', 'estado_postulacion')]),
        ),
        migrations.AlterUniqueTogether(
            name='convocatoriapuesto',
            unique_together=set([('convocatoria', 'especialidad', 'familia_puesto', 'sub_especialidad', 'rango')]),
        ),
    ]
