# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'permissions': (('autorizar_convocatoria', 'Puede autorizar convocatoria'), ('iniciar_convocatoria', 'Puede iniciar convocatoria')), 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
        migrations.AddField(
            model_name='peq_int_estado_convocatoria',
            name='fecha_comite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
