# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_auto_20180318_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peq_int_convocatoria_academico',
            name='porcentaje_cumplimiento',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
