# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_auto_20180319_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peq_int_estado_postulacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
