# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_auto_20180319_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'permissions': (('read_convocatoria', 'Puede ver convocatorias'), ('autorizar_convocatoria', 'Puede autorizar convocatoria'), ('iniciar_convocatoria', 'Puede iniciar convocatoria')), 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
    ]
