# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_auto_20180320_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
