# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_auto_20180321_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoriapuesto',
            name='sub_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_sub_especialidad'),
        ),
    ]
