# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_auto_20180324_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peq_int_convocatoria_cursos',
            name='porcentaje_cumplimiento',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_int_convocatoria_experiencia',
            name='porcentaje_cumplimiento',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
