# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_auto_20180324_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peq_int_estado_convocatoria',
            options={'verbose_name': 'Estado Convocatorias'},
        ),
    ]
