# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_peq_mae_tipo_atencion'),
        ('convocatorias', '0009_auto_20180324_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peq_int_estado_convocatoria',
            unique_together=set([('convocatoria', 'estado')]),
        ),
    ]
