# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0010_auto_20180326_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peq_int_convocatoria_academico',
            options={'permissions': (('add_criterio_academico', 'Puede agregar criterio academico'),), 'verbose_name': 'Convocatorias Acad\xe9mico'},
        ),
        migrations.AlterModelOptions(
            name='peq_int_convocatoria_cursos',
            options={'permissions': (('add_criterio_curso', 'Puede agregar criterio de cursos'),), 'verbose_name': 'Convocatorias curso'},
        ),
        migrations.AlterModelOptions(
            name='peq_int_convocatoria_experiencia',
            options={'permissions': (('add_criterio_laboral', 'Puede agregar criterio laboral'),), 'verbose_name': 'Convocatorias Experiencia'},
        ),
        migrations.AlterModelOptions(
            name='peq_int_estado_postulacion',
            options={'permissions': (('add_preseleccionados', 'Puede preseleccionar postulantes'), ('add_aprobados', 'Puede aprobar postulantes'), ('add_seleccionarpreseleccionado', 'Puede seleccionar postulantes preseleccionados'), ('add_tramitedocumentario', 'Puede agregar tramite documentario'), ('read_verificaciondomiciliaria', 'Puede ver verificacion domiciliaria'), ('read_contactabilidad', 'Puede ver cantactabilidad')), 'verbose_name': 'Estado Postulacion'},
        ),
    ]
