# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0012_auto_20180403_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peq_int_estado_postulacion',
            options={'permissions': (('add_preseleccionados', 'Puede preseleccionar postulantes'), ('add_aprobados', 'Puede aprobar postulantes'), ('add_seleccionarpreseleccionado', 'Puede seleccionar postulantes preseleccionados'), ('add_tramitedocumentario', 'Puede agregar tramite documentario'), ('read_verificaciondomiciliaria', 'Puede ver verificacion domiciliaria'), ('read_contactabilidad', 'Puede ver cantactabilidad'), ('read_preseleccionados', 'Puede ver preseleccionados'), ('read_seleccionados', 'Puede ver seleccionados'), ('read_aprobados', 'Puede ver aprobados')), 'verbose_name': 'Estado Postulacion'},
        ),
        migrations.AlterModelOptions(
            name='postulacionconvocatoria',
            options={'permissions': (('read_postulaciones', 'Puede ver postulaciones'),), 'verbose_name': 'Convocatorias Postulante'},
        ),
    ]
