# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_peq_mae_estados_postulacion_alias'),
        ('convocatorias', '0013_auto_20180405_0214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_cursos',
            unique_together=set([('convocatoria_puesto', 'tipo', 'nombre', 'tipo_registro')]),
        ),
    ]
