# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_peq_mae_estados_postulacion_alias'),
        ('convocatorias', '0014_auto_20180405_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_experiencia',
            unique_together=set([('convocatoria_puesto', 'especialidad', 'familia_puesto', 'sub_especialidad', 'rango', 'tipo_registro')]),
        ),
    ]
