# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_auto_20180406_1350'),
        ('convocatorias', '0015_auto_20180406_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peq_int_convocatoria_academico',
            unique_together=set([('convocatoria_puesto', 'familia_carrera', 'carrera', 'grado', 'estado_grado')]),
        ),
    ]
