# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0016_auto_20180406_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
