# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEQ_MAE_carreras',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_centros_estudio',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de estudios',
                'verbose_name_plural': 'Centro de estudios',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_criterios_aprobacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('alias', models.CharField(max_length=25, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Criterios de Aprobaci\xf3n',
                'verbose_name_plural': 'Criterios de Aprobaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_cursos',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cursos',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_departamentos',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_detalle_documentacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Detalle Documentaci\xf3n',
                'verbose_name_plural': 'Detalle Documentaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_distritos',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_documentacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Documentaci\xf3n',
                'verbose_name_plural': 'Tipo Documentaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_duracion_contrato',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Duraci\xf3n Contrato',
                'verbose_name_plural': 'Duracion Contrato',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_empresas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_estado_grado',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado Grado',
                'verbose_name_plural': 'Estados Grado',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_estados_convocatoria',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado convocatoria',
                'verbose_name_plural': 'Estados convocatoria',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_estados_postulacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de postulaci\xf3n',
                'verbose_name_plural': 'Estados de postulaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_familia',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_familia_carreras',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Familia carreras',
                'verbose_name_plural': 'Familia carreras',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_familia_grado',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Familia Grado',
                'verbose_name_plural': 'Familia Grados',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_familia_puesto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Familia Puesto',
                'verbose_name_plural': 'Familia Puestos',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_grado',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_grado')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_lugares',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_provincias',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_departamentos')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_rango_seleccion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('orden', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('minimo', models.PositiveIntegerField(blank=True, null=True)),
                ('maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rango postulante',
                'verbose_name_plural': 'Rango postulante',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_rangos',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rango',
                'verbose_name_plural': 'Rangos',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_remuneracion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Remuneracion',
                'verbose_name_plural': 'Remuneraciones',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_requisitos',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Requisitos Convocatoria',
                'verbose_name_plural': 'Requisitos Convocatoria',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_sub_especialidad',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia')),
            ],
            options={
                'verbose_name': 'Sub especialidad',
                'verbose_name_plural': 'Sub especialidades',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_tags',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_tiempo_experiencia',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.IntegerField()),
                ('tipo', models.SmallIntegerField(blank=True, choices=[(1, 'MES'), (0, 'A\xd1O')], default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tiempo de experiencia',
                'verbose_name_plural': 'Tiempo de experiencia',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_tipo_cursos',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Cursos',
                'verbose_name_plural': 'Tipo Cursos',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_tipos_discapacidad',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipos de discapacidad',
                'verbose_name_plural': 'Tipos de discapacidad',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_tipos_documento',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='PEQ_MAE_tipos_documento_personales',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipos de documentos personales',
                'verbose_name_plural': 'Tipos de documentos personales',
            },
        ),
        migrations.AddField(
            model_name='peq_mae_familia',
            name='familia_puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_puesto'),
        ),
        migrations.AddField(
            model_name='peq_mae_distritos',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_provincias'),
        ),
        migrations.AddField(
            model_name='peq_mae_detalle_documentacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_documentacion'),
        ),
        migrations.AddField(
            model_name='peq_mae_carreras',
            name='familia_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_carreras'),
        ),
    ]
