# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peq_mae_rango_seleccion',
            options={'verbose_name': 'Porcentaje postulante', 'verbose_name_plural': 'Porcentajes postulante'},
        ),
    ]
