# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-29 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_peq_mae_provincias_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peq_mae_provincias',
            name='orden',
        ),
    ]
