# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_remove_peq_mae_provincias_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='peq_mae_estados_postulacion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
