# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_peq_mae_estados_postulacion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='peq_mae_estados_postulacion',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
