# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_peq_mae_estados_postulacion_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peq_mae_carreras',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_criterios_aprobacion',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_estado_grado',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_estados_postulacion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_familia',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_familia_carreras',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_familia_grado',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_familia_puesto',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_grado',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_rango_seleccion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peq_mae_rangos',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
