# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_auto_20180406_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='peq_mae_estados_convocatoria',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
