# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_peq_mae_estados_convocatoria_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peq_mae_documentacion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
