# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
        ('usuarios', '0004_auto_20180317_0216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursospostulantes',
            unique_together=set([('persona', 'tipo', 'nombre')]),
        ),
        migrations.AlterUniqueTogether(
            name='documentospersonal',
            unique_together=set([('persona', 'tipo')]),
        ),
    ]
