# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180319_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioneducativa',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_carreras'),
        ),
        migrations.AlterField(
            model_name='informacioneducativa',
            name='familia_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_familia_carreras'),
        ),
    ]
