# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20180326_2112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursospostulantes',
            unique_together=set([]),
        ),
    ]
