# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20180405_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='declaro',
            field=models.BooleanField(default=False),
        ),
    ]
