# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-28 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_persona_declaro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursospostulantes',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursospostulantes',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursospostulantes',
            name='hasta_actualidad',
            field=models.BooleanField(default=False),
        ),
    ]
