# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_peq_mae_ingles'),
        ('usuarios', '0011_auto_20180427_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ingles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.PEQ_MAE_ingles'),
        ),
    ]
